spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:june;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

## STATIC KEY
secrete:
  jwt_key: "H5+BLGxTtZ2+Ptabl/ggOPgI8HG8jdNEHvAqoHf1kvw="