spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:mem:june
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

## STATIC KEY


environments:
  jwt_key: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIn0.NsqiK0Hi-XMfh--iaXWibKHMUszRhjQp5KRC96FBkRs"
  local:
    url: http://localhost:8080
    name: Local
  dev:
    url: https://dev.example.com
    name: Developer Setup
  prod:
    url: https://another.example.com
    name: My Cool App

june:
  hello: "testName"