spring:
  session:
    jdbc:
      initialize-schema: always
  #  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:mariadb://sorma.asuscomm.com:3307/junehouse?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: june
    password: crain008*
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: none
    defer-datasource-initialization: true
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

## STATIC KEY
secrete:
  jwt_key: "H5+BLGxTtZ2+Ptabl/ggOPgI8HG8jdNEHvAqoHf1kvw="