### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "june",
  "email": "fnffn0607@naver.com",
  "password": "a1234"
}

### @no-redirect 로그인
POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=fnffn0607@naver.com&password=a1234&remember=1

### 메인페이지
GET http://localhost:8080