### HTTP TEST 요청

GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkyNjk1NDc3LCJleHAiOjE2OTI2OTkwNzd9.9wYpHnVregO9LUDIlL8SBAze-CMbtPSq3lRa9TN_VpI